version: '3'
services:
  mongodb_container:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: techdebt
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  interview-service:
    ports:
      - 8080:8080/tcp
    depends_on:
      - mongodb_container
    build:
      context: ./
      dockerfile: Dockerfile
volumes:
  mongodb_data_container:

